name = "OMJulia"
uuid = "0f4fe800-344e-11e9-2949-fb537ad918e1"
authors = ["Martin Sjölund <martin.sjolund@liu.se>", "Arunkumar Palanisamy <arunkumar.palanisamy@liu.se>", "John Tinnerholm <JKRT@users.noreply.github.com>", "Andreas Heuermann <38031952+AnHeuermann@users.noreply.github.com>"]
version = "1.0.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
Automa = "1"
DataFrames = "1"
LightXML = "0.8, 0.9"
Random = "1"
ZMQ = "1"
julia = "1.10"
