name: Regression Tests

on:
  push:
    branches: ['master', 'maintenance/*']
  schedule:
    - cron: "25 4 * * 3" # Every Wednesday at 04:25
  workflow_dispatch:

jobs:
  regression-test:
    if: github.repository == 'OpenModelica/OMJulia.jl' # Run only on OpenModelica/OMJulia.jl to prevent spamming forks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6', '1.9']
        julia-arch: ['x64']
        os: ['ubuntu-latest', 'windows-latest']
        omc-version: ['stable', 'nightly', '1.21']

    steps:
      - uses: actions/checkout@v4

      - name: "Set up OpenModelica Compiler"
        uses: AnHeuermann/setup-openmodelica@v0.7
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            'Modelica 4.0.0'

      - run: "omc --version"

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - name: Cache Julia
        uses: julia-actions/cache@v1

      - name: "Build OMJulia"
        uses: julia-actions/julia-buildpkg@v1

      - name: Install dependencies
        run: julia --project=regression-tests/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: "Run regression test"
        shell: bash
        run: julia --project=regression-tests/. -e 'include("regression-tests/regressionTests.jl"); runTests(libraries, models)'

      - name: Archive FMUs
        uses: actions/upload-artifact@v3
        with:
          name: fmu-export
          path: regression-tests/temp/**/*.fmu
