name: Test

on:
  push:
    branches: ['master', 'maintenance/*']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.9']
        julia-arch: ['x64']
        os: ['ubuntu-latest', 'windows-latest']
        omc-version: ['stable']

    steps:
      - uses: actions/checkout@v4

      - name: "Set up OpenModelica Compiler"
        uses: AnHeuermann/setup-openmodelica@v0.6
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            'Modelica 4.0.0'

      - run: "omc --version"

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - name: Cache Julia
        uses: julia-actions/cache@v1

      - name: "Build OMJulia"
        uses: julia-actions/julia-buildpkg@v1

      - name: "Test OMJulia"
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
